### ISSUE TITLE
When a callback raises an exception, should it be treated as complete?

### ISSUE THREAD

**Issue by Akeit0** [AnnulusGames/LitMotion#10]
現在、Callbackが例外を吐くとき、Logを出してそのままですが、
Complete扱いにした方がいいと思います。もしくはOptionで選べるようにするとか。
MotionCallbackDataのCancellationTokenはそのためにもあるとは思いますが、どうでしょうか?
またOperationCanceledExceptionを特別扱いして、例外を無視することも考えられます。(これもOption?)
UnityObjectにBindする系もnullを例外扱いさせるとよいと思います。

**Comment by AnnulusGames** [comment]
> 現在、Callbackが例外を吐くとき、Logを出してそのままですが、
Complete扱いにした方がいいと思います。

内容の意図をいまいち理解できていないのですが、これはどのような具体的に挙動を想定していますか？

OperationCanceledExceptionの無視に関してはコールバック内部でtry-catchを記述し、例外をスルーする処理を書けば可能だであるため、わざわざオプションを追加する必要はないと思います。(CancellationTokenはUniTaskとのスムーズな統合のために組み込まれています。)

**Comment by Akeit0** [comment]
一度例外を出した後、毎フレーム例外を出し続ける可能性があるため、それを避けたい場合もあるかなと思いコメントしました。

**Comment by AnnulusGames** [comment]
Unityのコンポーネントに対するBindの拡張はnullチェックを入れてエラーが起きないような仕様になっていますが、こちらに対しては警告のログを表示することを検討しています。例外を投げる方がより厳密なハンドリングが可能ですが、トゥイーンライブラリの多くはオブジェクトが破棄された後もそのまま動作する仕様になっているため、それらに倣った方が良いかと思われます。

**Comment by Akeit0** [comment]
Tweenライブラリとしての一般的な仕様に倣うということであればcloseします

**Comment by AnnulusGames** [comment]
> 一度例外を出した後、毎フレーム例外を出し続ける可能性があるため

なるほど、理解しました。確かにそのような状況はあり得るためエラー時にキャンセルするオプションを追加しても良いかもしれません。
考えられるAPIは以下のようなものですが、いかがでしょうか。

```cs
LMotion.Create(0f, 10f, 2f)
    .WithCancelOnError()
    .Bind(...);
```

**Comment by Akeit0** [comment]
UniTask側にcancelを知らせた方が良いかもしれないですね
ちょっとユーザーにはわかりづらいことになるかもしれないですが

**Comment by Akeit0** [comment]
いやすみません。単純にOnCopmleteが呼ばれないだけですね

**Comment by AnnulusGames** [comment]
#13 でWithCancelOnErrorを追加しました。
Cancel周りでUniTaskとのとの連携が上手く行われていないために発生する不具合を発見しましたが、これはこのissueとは関係ないので一旦Closeします。

**Comment by Akeit0** [comment]
了承したあとで申し訳ないですが、OnCompleteにDispose処理を書いている可能性があるので、enum ErrorBehaviourが適切だと思いました。
