### ISSUE TITLE
Wrong dependency on package.json

### ISSUE THREAD

**Issue by from2001** [AnnulusGames/LitMotion#124]
Hi, thank you for the great library.

When I try to install LitMotion with OpenUPM, I got the following error.

```sh
openupm add com.annulusgames.lit-motion
WARN 404 version 1.0.0 is not a valid choice of 0.0.12-preview.2, 0.0.12-preview.5, 0.0.12-preview.8, 0.0.12-preview.10, 0.0.12-preview.11, 0.0.12-preview.13, 0.0.12-preview.17, 0.0.12-preview.19, 0.0.12-preview.20, 1.0.0-preview.1, 1.0.1, 1.1.0-preview.1, 1.1.0, 1.2.1, 1.2.4, 1.2.5, 1.2.6, 1.3.1, 1.3.2
```

You specify `com.unity.mathematics` `1.0.0` as dependency in [package.json](https://github.com/AnnulusGames/LitMotion/blob/b2bcc26e4d8a708fa24c493253785363424fd291/src/LitMotion/Assets/LitMotion/package.json#L13), but it seems that version `1.0.0` doesn't exist. `1.2.6` would be the good option instead.

You can see the all available versions of the package [here](https://yamaguchimasahiro.com/apps/upm2rss.php?name=com.unity.mathematics) with  [upm2rss](https://github.com/from2001/upm2rss).

**Comment by AnnulusGames** [comment]
Changed the version specified to `1.0.1`. This should now work.
