### ISSUE TITLE
When the editor replays, Updating Runner may have a negative deltaTime

### ISSUE THREAD

**Issue by Rotanticu** [AnnulusGames/LitMotion#130]
RunnerCache will cache the Updating Runner, so replaying it will not create a new Updating Runner, only Reset()
However, the Reset() function of the Updating Runner does not reset the time, which can result in an error in calculating the first frame time
The time should be reset in the Reset() function of the Updating Runner Like this
`        public void Reset()
        {
            storage.Reset();
            prevTime = 0d;
            prevUnscaledTime = 0d;
            prevRealtime = 0d;
        }
`

**Comment by AnnulusGames** [comment]
Fixed in #148
