### ISSUE TITLE
Foldout.toggleOnLabelClick Only Unity6+ is supported  -> v2.0

### ISSUE THREAD

**Issue by BadZhang** [AnnulusGames/LitMotion#174]
[Foldout.toggleOnLabelClick](https://docs.unity3d.com/6000.0/Documentation/ScriptReference/UIElements.Foldout.html) Only Unity6+ is supported

Unity 2022.3.X -> Not supported.
![image](https://github.com/user-attachments/assets/10b65a10-e176-469d-9c6e-1bd096a97579)

**Comment by AnnulusGames** [comment]
Fixed in #176
