### ISSUE TITLE
[Proposal] Make await handle; to throw OperationCanceledException when MotionHandle.Cancel.

### ISSUE THREAD

**Issue by Akeit0** [AnnulusGames/LitMotion#18]
It is odd that handle.ToUniTask(cts.Token) does not throw an exception when the MotionHandle itself is canceled, even though handle.ToUniTask(cts.Token) throws an exception on CancellationTokenSource cancellation.

**Comment by Akeit0** [comment]
```cs
public void OnMotionCanceled()
{
    if (cancellationToken.IsCancellationRequested)
    {
        canceled = true;
    }
    if (canceled)
    {
        core.TrySetCanceled(cancellationToken);
    }
    else
    {
        core.TrySetCanceled();
       // core.TrySetResult(AsyncUnit.Default);
    }
}
```

**Comment by AnnulusGames** [comment]
It is certainly more natural to cancel the await, so we changed the behavior to do so. (#23)
