### ISSUE TITLE
Can Unity 2020 version use this library? 

### ISSUE THREAD

**Issue by yqsas** [AnnulusGames/LitMotion#32]
How is the compatibility?

**Comment by Akeit0** [comment]
https://github.com/AnnulusGames/LitMotion#requirements

**Comment by AnnulusGames** [comment]
LitMotion relies on several DOTS packages for advanced optimization based on data-oriented design.
It may be possible to use older Unity versions if the package requirements are met, but there is no guarantee that it will work. (Editor versions earlier than the recommended version have not been tested and there are no plans to support them.)

**Comment by Akeit0** [comment]
Since it is using C#9 or later syntax, 2021.2 seems to be the minimum version that will work.
