### ISSUE TITLE
Any plan for preset or reusable configuration?

### ISSUE THREAD

**Issue by laicasaane** [AnnulusGames/LitMotion#44]
Do you have plan for preset configuration that can be saved in a MonoBehaviour or ScriptableObject so we can mirror the functionality of DOTween Animation?

![image](https://github.com/AnnulusGames/LitMotion/assets/1594982/785426a4-b2d8-4667-a393-d5b9984d7e9a)

**Comment by AnnulusGames** [comment]
I'm skeptical that LitMotion needs such a feature. I've been using DOTweenPro for a long time, but I've never used the DOTween Animation component. I think Timeline is a better way to build animations without writing code. (You can easily create tweens on Timeline by using [TweenPlayables](https://github.com/AnnulusGames/TweenPlayables).)
