### ISSUE TITLE
The () is missing in Doc's Code Example

### ISSUE THREAD

**Issue by amenonegames** [AnnulusGames/LitMotion#72]
Code example in following  docs is 
`if (handle.IsActive) ...`

But maybe  `if (handle.IsActive())` is currect.
I think the () is missing.

https://github.com/AnnulusGames/LitMotion/blob/main/docs/articles/ja/controlling-motion.md/#%E3%83%A2%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E5%AD%98%E5%9C%A8%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF

https://github.com/AnnulusGames/LitMotion/blob/main/docs/articles/en/controlling-motion.md/#motion-existence-check

**Comment by AnnulusGames** [comment]
Fixed in #73.
